#!/usr/bin/env python3

import requests, re, yaml, time

with open("/etc/_config.yaml", 'r') as yamlfile:
    cfg = yaml.load(yamlfile)

s = requests.Session()
r = s.get('https://trakt.tv/auth/signin')

matchme = 'meta name="csrf-token" content="(.*)" '
csrf = re.search(matchme,str(r.text))

s.post('https://trakt.tv/auth/signin', data={
    "user[login]" : cfg['trakt']['login'],
    "user[password]" : cfg['trakt']['password'],
    "user[remember_me]" : 1,
    "authenticity_token" :  csrf.group(1),
    "commit" : "Sign In"
    })

pin_req = s.get('https://trakt.tv/pin/478')
trakt_pin = pin_req.url.split('=')[1]

plex_token_headers = {'X-Plex-Token': cfg['plex']['token']}

trakt_req = requests.get('http://localhost:32400/video/trakt/:/prefs/set?sync_idle_defer=false&scrobble_duplication_period=0&filter_networks=%2A&sync_idle_delay=0&start_scrobble=true&sync_ratings=0&sync_run_library=true&filter_sections=%2A&activity_mode=2&sync_clean_collection=false&sync_playback=1&sync_run_interval=1&sync_instant_actions=true&pin='+trakt_pin, headers=plex_token_headers)

sync_from_trakt = requests.get('http://localhost:32400/video/trakt/sync/pull?account_id=1&t='+str(round(time.time(),1)), headers=plex_token_headers)
